# PCA_detail

In [1]:
import numpy as np

In [2]:
class PCA:
    def __init__(self, X, k):
        self.X = X
        self.k = k
        self.centr_X = []
        self.cov = []
        self.U = []
        self.Z = []
        
        self.centr_X = self._centralized()
        self.cov = self._cov()
        self.U = self._U()
        self.Z = self._Z()

    def _centralized(self):
        print('样本矩阵X:\n', self.X)
        centr_X = []
        mean = np.array([np.mean(feature) for feature in self.X.T])
        print('样本集的特征均值:\n', mean)
        centr_X = self.X - mean
        print('样本矩阵X的中心化:\n', centr_X)
        return centr_X

    def _cov(self):
        n = self.centr_X.shape[0]
        Cov = np.dot(self.centr_X.T, self.centr_X)/(n - 1)
        print('样本矩阵X的协方差矩阵:\n', Cov)
        return Cov

    def _U(self):
        a, b = np.linalg.eig(self.cov)
        print('协方差矩阵的特征值:\n', a)
        print('协方差矩阵的特征向量\n', b)
        ind = np.argsort(-a)
        UT = [b[:,ind[i]] for i in range(self.k)]
        U = np.transpose(UT)
        print('%d阶降维转换矩阵U:\n'%self.k, U)
        return U
    
    def _Z(self):
        Z = np.dot(self.X, self.U)
        print('X shape:', self.X.shape)
        print('U shape:', self.U.shape)
        print('Z shape:', Z.shape)
        print('样本矩阵X的降维矩阵:\n', Z)
        return Z

In [3]:
X = np.random.randint(1, 100, (5, 3))
k = np.shape(X)[1]-1
pca = PCA(X, k)

样本矩阵X:
 [[97 41 11]
 [13 20 44]
 [66 27 86]
 [63 41 46]
 [25 39 72]]
样本集的特征均值:
 [52.8 33.6 51.8]
样本矩阵X的中心化:
 [[ 44.2   7.4 -40.8]
 [-39.8 -13.6  -7.8]
 [ 13.2  -6.6  34.2]
 [ 10.2   7.4  -5.8]
 [-27.8   5.4  20.2]]
样本矩阵X的协方差矩阵:
 [[1147.2   176.65 -415.55]
 [ 176.65   91.8   -88.85]
 [-415.55  -88.85  834.2 ]]
协方差矩阵的特征值:
 [1462.73035154  548.16561463   62.30403384]
协方差矩阵的特征向量
 [[ 0.81645992  0.55815204 -0.14784958]
 [ 0.1414848   0.05486082  0.98841911]
 [-0.55979929  0.82792306  0.03417837]]
2阶降维转换矩阵U:
 [[ 0.81645992  0.55815204]
 [ 0.1414848   0.05486082]
 [-0.55979929  0.82792306]]
X shape: (5, 3)
U shape: (3, 2)
Z shape: (5, 2)
样本矩阵X的降维矩阵:
 [[ 78.83969717  65.4971951 ]
 [-11.18749375  44.78180759]
 [  9.5637055  109.52065987]
 [ 31.48708464  75.49733291]
 [-14.37614357  75.70383337]]


# PCA Invoked by sklearn

In [4]:
from sklearn.decomposition import PCA

In [5]:
X = np.random.randint(1, 100, (6, 4))
print(X)
pca = PCA(n_components=3)
pca.fit(X)
new_X = pca.fit_transform(X)
print(pca.explained_variance_ratio_)
print(new_X)

[[88 64 23 16]
 [99 30 49  7]
 [20 22 77 80]
 [31 48 20 58]
 [67 81 36 94]
 [61 45 84 16]]
[0.55137083 0.31413749 0.09776351]
[[-40.92899318  26.70943143   6.60201772]
 [-53.44159479 -10.03483451  -0.3495946 ]
 [ 54.03101898 -37.98878058   0.52496592]
 [ 26.56299106  14.34141356  30.46134245]
 [ 34.62420441  42.79469292 -24.5587158 ]
 [-20.84762647 -35.82192282 -12.68001569]]
